import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { onest, twidGrotesk } from "@/fonts/fonts";
import { ThemeProvider } from "@/components/theme-provider"
import Navbar from "@/components/layout/navbar/navbar";
import "./globals.css";
import CursorDot from "@/components/layout/cursorDot/cursorDot";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${geistSans.variable} ${geistMono.variable} ${onest.variable} ${twidGrotesk.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <CursorDot />
          <div className="absolute w-full">
            <Navbar />
          </div>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}

