import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { drukWide, onest, twidGrotesk } from "@/fonts/fonts";
import { ThemeProvider } from "@/components/theme-provider"
import Navbar from "@/components/layout/navbar/navbar";
import { LoaderWrapper } from "@/components/layout/loader/loader";
import "./globals.css";
import CursorDot from "@/components/layout/cursorDot/cursorDot";
import Footer from "@/components/layout/footer/footer";
import PageTransition from "@/components/layout/pageTransition/pageTransition";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${geistSans.variable} ${geistMono.variable} ${onest.variable} ${twidGrotesk.variable} ${drukWide.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <PageTransition />

          <CursorDot />
          <Navbar />

          <main className="pt-20">
            <LoaderWrapper>
              {children}
            </LoaderWrapper>
          </main>

          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}

